### ISSUE TITLE
Failed to build project due to egui compilation problem

### ISSUE THREAD

**Issue by danieldeankon** [optozorax/portal#2]
`$ git clone https://github.com/optozorax/portal`
`$ cd ./portal`
`$ cargo run --release`

Appears to build as expected until:

```
error[E0433]: failed to resolve: could not find `ComboBox` in `egui`
  --> src/gui/combo_box.rs:51:15
   |
51 |         egui::ComboBox::from_label("")
   |               ^^^^^^^^ not found in `egui`
   |
help: consider importing this struct
   |
1  | use macroquad::ui::widgets::ComboBox;
   |

error[E0599]: no function or associated item named `new` found for struct `egui::Slider<'_>` in the current scope
   --> src/gui/animation.rs:187:44
    |
187 | ...                   ui.add(Slider::new(value, *min..=*max).clamp_to_range(true));
    |                                      ^^^ function or associated item not found in `egui::Slider<'_>`

```
(Further error messages omitted)

I saw in a recent commit that egui was updated to 0.11.0 in your project, so I went into the cargo.toml file and changed the line `egui = "0.10.0"` to `egui = "0.11.0"`. That didn't work, so I changed it back and then tried putting in the import suggested by the help text into combo_box.rs. That didn't work either.

I then ran `$ git checkout cfc2277` to check out the commit https://github.com/optozorax/portal/commit/cfc22779d62ae9d66268246b3279fd0faa828dd1 and tried building it again. Building it worked, but I got a segmentation fault when running it.

```
$ cargo run --release
   Compiling portal v0.1.4 (/home/daniel/git/portal)
    Finished release [optimized] target(s) in 36.90s
     Running `target/release/portal`
GLX: failed to create GL context
Segmentation fault (core dumped)
```

This is likely to be an issue around me having outdated drivers or missing a package in my Linux distribution so I will research this error and try again some other time.

**Comment by danieldeankon** [comment]
Just for reference, at the time of writing the master branch is at https://github.com/optozorax/portal/commit/e9de87d244d4032f937f7f0170d731058c1f915a

**Comment by optozorax** [comment]
Yeah, sorry, the latest commit broke everything, I didn't expect that anyone will compile code by themselves, you should use https://github.com/optozorax/portal/commit/cfc22779d62ae9d66268246b3279fd0faa828dd1.

I believe this could help you with drivers and etc.: https://github.com/not-fl3/miniquad#linux

**Comment by danieldeankon** [comment]
I forgot to follow up on this, but I ended up managing to run it with no problems. A computer restart fixed whatever driver issue I was having earlier.
